# Generated by Django 3.1.5 on 2021-01-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0002_auto_20210121_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='company',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
