# Generated by Django 3.1.5 on 2021-01-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0003_auto_20210127_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together={('name', 'pieces', 'company')},
        ),
    ]
