# Generated by Django 3.1.5 on 2021-02-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0004_auto_20210129_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='checked_out_by_last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='owner_last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
