# Generated by Django 3.1.5 on 2021-02-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0005_auto_20210207_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='checked_out_by_last_name',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='owner_last_name',
            field=models.CharField(max_length=20),
        ),
    ]
