# Generated by Django 3.1.5 on 2021-02-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0006_auto_20210207_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='checked_out_by_last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
