# Generated by Django 3.1.5 on 2021-02-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0007_puzzle_checked_out_by_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='checked_out_by_last_name',
            new_name='user_last_name',
        ),
    ]
