# Generated by Django 3.1.5 on 2021-02-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_share', '0008_auto_20210208_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
